= AsciiDog

AsciiDog is an implementation in http://groovy-lang.org[Groovy] of the
popular lightweight markup language http://asciidoc.org[AsciiDoc]
(another popular implementation is http://asciidoctor.org[Asciidoctor]).

There is no official AsciiDoc grammar yet, but people are
http://discuss.asciidoctor.org/Asciidoc-syntax-definition-td1920.html[showing interest]
to create one.

This project is still in very early stage, and not ready for any
kind of usage.

== Quick Start

[source, shell]
----
# ePug library
git clone https://github.com/SuperMMX/epug.git

# build and publish
cd epug
./gradlew publishToMavenLocal

# AsciiDog
git clone https://github.com/SuperMMX/asciidog.git

# Convert README.adoc to html5 and epub
cd asciidog
./gradlew run -Pargs="-i README.adoc -b html5,epub -o build"

# View build/README.html and build/README.epub
----

== Features

=== Parser

* Structure
** Document header
*** Title
*** Author
*** Basic document attribute
** General block
*** Attribute
*** ID
*** Title
** Section
** Include
* List
** Ordered list
** Unordered list
* Block Macro
** Image
* Inline
** Formatting
*** Strong
*** Emphasis
** Attribute reference
** Cross reference

=== Converter

* AST Walker
* Chunked output

=== Backend & Renderer

* Template-based backend
* Basic HTML5 backend
* Basic ePub3 backend

//

* Support vertical writing mode by passing option `-Ooutput-writing-mode=vrl`

=== Builder

AsciiDoc builder to create the AST easily

=== Plugin Infrastructure

Backend: To render and save the rendered result

There are different types of plugins:

* Parser: To parse text into AST nodes
* Builder: To create AST nodes with DSL
* Processor: To create, delete and transform the AST nodes
* Renderer: To render AST nodes for a backend

Sample plugin suite:

* CriticMarkup, including parsers, builders and templates for html5 backend

== TODO

* Table
* Link
* Delimited block
* Create include node instead of hiding it in reader

== Issues

=== Rendering

